In [1]:
#TRUPTI  PATIL


#1
import numpy as np
x = int(input("enter a number"))

y = np.random.randint(0,x,(1,20))
y

enter a number20


array([[15, 19,  9,  5,  3, 10,  8,  2,  8, 14,  2,  5, 17,  9,  2,  3,
         8,  2,  2, 11]])

In [ ]:
#2
arr = np.arange(300, 500, 10).reshape(4,5)
print (arr)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


In [ ]:
#3
import numpy as np
matrix = np.random.randint(-1000,1000, (20,20))
matrix

array([[  -47,   -67,   -54,  -627,    53,  -368,  -979,  -911,   763,
          377,   233,   969,   486,   344,  -395,   346,   195,    99,
         -783,  -261],
       [ -925,  -840,   761,    69,  -560,  -255,  -895,   383,   688,
          757,   100,   121,   987,  -469, -1000,   200,  -212,   619,
         -298,   -49],
       [  386,  -777,   863,  -901,  -131,   817,   294,  -418,   -26,
          795,   577,  -998,  -751,   996,  -280,   929,  -600,  -400,
          498,   718],
       [  -75,  -613,   350,   222,   891,   706,   541,   193,   192,
          891,  -877,  -168,   -97,  -385,   351,  -167,    97,  -654,
          -46,  -236],
       [ -518,  -336,   880,   455,   474,  -792,   161,  -156,   516,
         -208,  -445,   379,  -577,  -200,     2,  -498,  -389,   234,
         -135,  -176],
       [ -857,  -843,  -905,   901,   721,   221,  -392,  -915,  -484,
         -228,  -435,   342,   174,   996,   101,    99,  -959,    39,
          901,  -224],
       [ -

In [ ]:
np.max(matrix)

996

In [ ]:
np.min(matrix)

-1000

In [ ]:
np.mean(matrix)

8.055

In [ ]:
#4
arr1 = np.random.randint(-50,50,(5,5)) 
print (arr1)
rows, columns = arr1.shape
arr1[4:] = [-1]*columns
print(arr1)
for number in arr1[:-3,columns-2:]:
    number *= 2
print(arr1)

[[ 40  31 -47 -46  48]
 [-27 -10 -22   4  35]
 [ 44 -32   4 -14   5]
 [ -1  17  39   6 -21]
 [ 26  41  18  19  38]]
[[ 40  31 -47 -46  48]
 [-27 -10 -22   4  35]
 [ 44 -32   4 -14   5]
 [ -1  17  39   6 -21]
 [ -1  -1  -1  -1  -1]]
[[ 40  31 -47 -92  96]
 [-27 -10 -22   8  70]
 [ 44 -32   4 -14   5]
 [ -1  17  39   6 -21]
 [ -1  -1  -1  -1  -1]]


In [ ]:
#5
import numpy as np
num = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4 ,-6, 90, 10] ,[25 ,45 ,34, 22 ,12], [13 ,24, 22 ,32, 37]])
n = 0 
r = 0


print(np.where(num < n,r,num))

print(np.where( num % 2 == 1,25,num))

[[ 2 30 20  0  0]
 [ 3  4 40  0  0]
 [ 0  4  0 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]]
[[ 2 30 20 -2 -4]
 [25  4 40 25 -2]
 [25  4 -6 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]
